### ISSUE TITLE
This is very basic not even functional project

### ISSUE THREAD

**Issue by yarodevuci** [SwiftisLife/FirebaseChat#2]
Are you planing to update it and adding a normal functionality ?

**Comment by SwiftisLife** [comment]
What are some things you'd like to see in this project?

**Comment by yarodevuci** [comment]
Well, I am working on similar chat using firebase. The main cool thing is to have a contacts list first and when you add a contact, you select it, Message window opens up, you type some message and go back you have a conversation created between me and other person.

**Comment by SwiftisLife** [comment]
Yeah, you're definitely right! I built this when I first began doing stuff with real-time database stuff so it I was just learning about that, but it's something I've been thinking about a lot because I do love everything about messengers. Loving the constructive feedback 👍

**Comment by yarodevuci** [comment]
@SwiftisLife Hey do you want to keep working on your own project or you would like to become a contributor for my messenger and we can work on it together. What do you think ?

**Comment by SwiftisLife** [comment]
@yarodevuci I'd be really interested in collaboration. At this time all my projects are in Swift 2.3 but I will be using Xcode 8 today to start building stuff in Swift 3.

**Comment by SwiftisLife** [comment]
Also, if you want to look at something I've been working on, ignore this repository completely. Take a look at: https://github.com/SwiftisLife/FirebaseIM

It's got user authentication, verification e-mail functionality etc... Unlike this one it does not have presence management but I'm going to add a contact list to it today. I'll probably just delete this repository altogether as it has an older version of Firebase anyway. But yeah **FirebaseIM** is what I've been working on for the most part, same exact messenger just updated version (still Swift 2.3 though)
